# Generated by Django 4.1.3 on 2022-11-14 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='raitingAuthor',
            new_name='ratingAuthor',
        ),
    ]
